spring:
  profiles:
    active: dev

#    hibernate:
#      ddl-auto: validate

  # 设置session会话存储类型
  session:
    # 内存
    store-type: hash_map


logging:
  level:
    org.hibernate.SQL: debug

# 关闭http basic认证
security:
  basic:
    enabled: false




